apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] > 0.97
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: >+
          sum(
            rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status!~"[4-5].*"}[120s]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[120s])
          )
